spring:
  application:
    name: SPRINGJPA

  redis:
    host: ${REDIS_HOST:localhost}     
    port: ${REDIS_PORT:6379}            
    username: ${USER_NAME:}
    password: ${REDIS_PASSWORD}
    ssl: ${SLL:false}                 

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC

logging:
  level:
    org.springframework: DEBUG

server:
  port: ${PORT:8080}

select_key: ${SELECT_KEY}
gmail_key: ${GMAIL_USERNAME}
gmail_app_password: ${GMAIL_APP_PASSWORD}
public_endpoints: ${PUBLIC_ENDPOINTS}