# spring:
#   application:
#     name: SPRINGJPA

#   datasource:
#     url: ${DB_URL}
#     username: ${DB_USERNAME}
#     password: ${DB_PASSWORD}

#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect
#         format_sql: true
#         use_sql_comments: true
#         jdbc.time_zone: UTC

# logging:
#   level:
#     org.springframework: DEBUG

# server:
#   port: ${PORT:8080}

# select_key: ${SELECT_KEY}
# gmail_key: ${GMAIL_USERNAME}
# gmail_app_password: ${GMAIL_APP_PASSWORD}
# cloudinary:
#   cloud-name: your_cloud_name
#   api-key: your_api_key
#   api-secret: your_api_secret


spring:
  datasource:
    url: jdbc:postgresql://dpg-d4uemq9r0fns7390kusg-a.oregon-postgres.render.com:5432/ttit
    username: ttit_user
    password: tarLtODsmnJveK9kCex8fmoLVcSCQfQQ

  redis:
    host: redis-14131.crce262.us-east-1-1.ec2.cloud.redislabs.com
    port: 14131
    username: default
    password: soiBqC3U9WZ2zxaevWxKHEiGwQ7VfLhZ
    ssl: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: UTC

logging:
  level:
    org.springframework: DEBUG

server:
  port: ${PORT:8080}

jwt:
  select_key: "d98206d268d7ef846b1bc905ae19667507ac98cced24126bab0e2cc2b5291ad2712485f667fb98ecc77f370b0faa363b889b4aa6b3dd8f764c7961a44d445955"

gmail:
  gmail_key: "thetruongit1236@gmail.com"
  gmail_app_password: "whmkcnjoguzlchmr"

api:
  #public_endpoints: ${PUBLIC_ENDPOINTS}
  public_endpoints: "/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**,/webjars/**,/configuration/**,api/auth/register,api/auth/login,api/auth/send-otp,
api/auth/verify-otp,api/auth/reset-password,api/auth/check/token,api/auth/check/RefreshToken,
api/permission/add/permission,api/role/add/new/role,api/role/get/all/role
"
cloudinary:
  cloud-name: Root
  api-key: 342825982688928
  api-secret: ePqlIDv8Up_gN43SFklnLYa7E5o
  secure: true 
